language: php

php:
  - 5.6
  - 7.1
  - nightly

before_script:
  - composer install

script:
  - vendor/bin/phpunit tests/Integration --coverage-clover=coverage.xml && bash <(curl -s https://codecov.io/bash) -c -F integration

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
